### ISSUE TITLE
Rename branch

### ISSUE THREAD

**Issue by distantnative** [getkirby/demo-manager#1]
@lukasbestle could we rename the branch to `main` or would we break something with the deployment to our demo setup?

**Comment by distantnative** [comment]
Also same question for the demerit itself https://github.com/getkirby/demokit

**Comment by bastianallgeier** [comment]
I think it's more critical for the demokit, but I could be wrong. @lukasbestle needs to evaluate that.

**Comment by lukasbestle** [comment]
✅
